config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/eosc-observatory:
      branch: main
      repo: https://github.com/madgeek-arc/eosc-observatory
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/eosc-observatory git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-buff-leopard.sh
        container: qc.acc_hilly-plum-bonobo
  QC.Doc:
    repos:
      github.com/madgeek-arc/eosc-observatory find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-amaranth-dugong.sh
        container: qc.doc_pasty-wisteria-saola
      github.com/madgeek-arc/eosc-observatory git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-alizarin-manatee.sh
        container: qc.doc_homey-emerald-drever
      github.com/madgeek-arc/eosc-observatory markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-pumpkin-vole.sh
        container: qc.doc_sleepy-coral-sparrow
  QC.Lic:
    repos:
      github.com/madgeek-arc/eosc-observatory licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-denim-moose.sh
        container: qc.lic_wheezy-chartreuse-elephant
  QC.Sty:
    repos:
      github.com/madgeek-arc/eosc-observatory checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-burgundy-dalmatian.sh
        container: qc.sty_bumpy-orange-ragdoll
      github.com/madgeek-arc/eosc-observatory hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-viridian-moorhen.sh
        container: qc.sty_woolly-ecru-turtle
      github.com/madgeek-arc/eosc-observatory jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-mustard-jaguar.sh
        container: qc.sty_lousy-firebrick-chinchilla
  QC.Ver:
    repos:
      github.com/madgeek-arc/eosc-observatory get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-scarlet-leopard.sh
        container: qc.ver_wheezy-burgundy-cockroach
timeout: 5400
