config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/eosc-observatory:
      branch: main
      repo: https://github.com/madgeek-arc/eosc-observatory
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/eosc-observatory git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-celadon-monkey.sh
        container: qc.acc_clammy-azure-bear
  QC.Doc:
    repos:
      github.com/madgeek-arc/eosc-observatory find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-pear-foxhound.sh
        container: qc.doc_surly-tan-leopard
      github.com/madgeek-arc/eosc-observatory git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-chartreuse-bat.sh
        container: qc.doc_tasty-black-hamster
      github.com/madgeek-arc/eosc-observatory markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-amber-coati.sh
        container: qc.doc_whiny-buff-mayfly
  QC.Lic:
    repos:
      github.com/madgeek-arc/eosc-observatory licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-burgundy-fowl.sh
        container: qc.lic_geeky-yellow-warthog
  QC.Sty:
    repos:
      github.com/madgeek-arc/eosc-observatory checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-magnolia-armadillo.sh
        container: qc.sty_hilly-thistle-impala
      github.com/madgeek-arc/eosc-observatory hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-saffron-snail.sh
        container: qc.sty_pretty-magnolia-dolphin
      github.com/madgeek-arc/eosc-observatory jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-periwinkle-mist.sh
        container: qc.sty_craggy-sangria-tang
  QC.Ver:
    repos:
      github.com/madgeek-arc/eosc-observatory get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-brown-seahorse.sh
        container: qc.ver_squeaky-scarlet-olm
timeout: 5400
